name: crypto_price_list
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #stacked
  stacked: ^2.2.8
  stacked_services: ^0.8.16

  #ui
  google_fonts: ^2.2.0

  #util
  http: ^0.13.4
  cached_network_image: ^3.2.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  stacked_generator: ^0.5.5
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/